---

- hosts: local
  tasks:
    - name: Invalidate ssh keys on first run
      shell: >
        test -e /etc/ssh/sshd_first_run ||
        rm /etc/ssh/ssh_host_* &&
        DEBIAN_FRONTEND=noninteractive dpkg-reconfigure openssh-server &&
        touch /etc/ssh/sshd_first_run

    - name: Create /var/run/sshd
      file:
        path: /var/run/sshd
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Update sshd_config
      template:
        owner: root
        group: root
        mode: "0644"
        src: openssh/sshd_config.j2
        dest: /etc/ssh/sshd_config
        validate: "/usr/sbin/sshd -t -f %s"
